using RingingBloom.NBNK;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace RingingBloom.Common
{
    public class Wem : BNKItem
    {
        private string _Name;
        public string name { get => _Name; set { _Name = value; OnPropertyChanged("name"); } }
        public uint id { get; set; }
        public uint length { get; set; }
        public uint languageEnum { get; set; }
        public new string Header { get => name; set { name = value; OnPropertyChanged("Header"); } }

        public byte[] file;
        public bool nameChanged = false;


        public Wem(string aName, string aId, BinaryReader aFile)
        {
            name = Path.GetFileName(aName);
            id = Convert.ToUInt32(aId);
            length = (uint)aFile.BaseStream.Length;
            file = aFile.ReadBytes((int)length);
            languageEnum = 0;
            aFile.Close();
        }

        public Wem(string aName, uint aID, byte[] aBinary)
        {
            name = aName;
            id = aID;
            length = (uint)aBinary.Length;
            file = aBinary;
            languageEnum = 0;
        }
        public Wem(string aName, uint aID, byte[] aBinary, uint lanEnum)
        {
            //the boolean only exists on pck, not bnk thus only needs to be generated by pck
            name = aName;
            id = aID;
            length = (uint)aBinary.Length;
            file = aBinary;
            languageEnum = lanEnum;
        }
    }
}
